### ISSUE TITLE
Refactor app/schema.js

### ISSUE THREAD

**Issue by bsingr** [jotaen/j4n.io#7]
There are a lot of type checks etc. in https://github.com/jotaen/j4n.io/blob/master/app/schema.js

Could it help to use Joi there?

**Comment by jotaen** [comment]
That could be worth a try.

The input/output functions are used for object manipulation and casting. I think Joi would not be the best choice here.

The validation function is currently only used in the tests to verify the responses, it is not used by the application itself. Perhaps it’s generally in the wrong place and it would be better to move it to the tests.

**Comment by jotaen** [comment]
@bsingr see https://github.com/jotaen/j4n.io/commit/d405812907e4ac8373cc5e1b413b0bf0d4f16736

**Comment by bsingr** [comment]
Okay, got it. Naming is important ;-)

+1 for rename to input/output
+1 for moving validation functions into tests (very important)
